[package]
name = "easyneural"
version = "0.1.0"
authors = ["mgr-inz-rafal <rchabowski@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.7"
rand_distr = "0.2"
serde_json = "1.0"
if_chain = "1.0"

[dev-dependencies]
approx = "0.3"